In [1]:
import pandas as pd
import numpy as np
import scipy
import math
import statistics as st
import scipy.stats as scst
import statsmodels.api
import matplotlib.pyplot as plt
import pylab

In [2]:
flextime = pd.read_csv('./flextime.txt', delimiter = ' ')

In [3]:
flextime

   employee  before  after
0         1      54     68
1         2      25     42
2         3      82     80
3         4      76     91
4         5      63     70
5         6      82     88
6         7      94     90
7         8      72     81
8         9      33     38
9        10      90     93

In [4]:
diff = flextime.after - flextime.before

In [12]:
scst.wilcoxon(x = diff, zero_method = 'wilcox', correction = False, alternative = 'greater')

WilcoxonResult(statistic=51.0, pvalue=0.0068359375)

In [13]:
gasoline = pd.read_csv('./gasoline.csv')

In [14]:
gasoline

        y     x1   x2     x3    x4    x5  x6  x7     x8    x9   x10  x11
0   18.90  350.0  165  260.0  8.00  2.56   4   3  200.3  69.9  3910    1
1   17.00  350.0  170  275.0  8.50  2.56   4   3  199.6  72.9  3860    1
2   20.00  250.0  105  185.0  8.25  2.73   1   3  196.7  72.2  3510    1
3   18.25  351.0  143  255.0  8.00  3.00   2   3  199.9  74.0  3890    1
4   20.07  225.0   95  170.0  8.40  2.76   1   3  194.1  71.8  3365    0
5   11.20  440.0  215  330.0  8.20  2.88   4   3  184.5  69.0  4215    1
6   22.12  231.0  110  175.0  8.00  2.56   2   3  179.3  65.4  3020    1
7   21.47  262.0  110  200.0  8.50  2.56   2   3  179.3  65.4  3180    1
8   34.70   89.7   70   81.0  8.20  3.90   2   4  155.7  64.0  1905    0
9   30.40   96.9   75   83.0  9.00  4.30   2   5  165.2  65.0  2320    0
10  16.50  350.0  155  250.0  8.50  3.08   4   3  195.4  74.4  3885    1
11  36.50   85.3   80   83.0  8.50  3.89   2   4  160.6  62.2  2009    0
12  21.50  171.0  109  146.0  8.20  3.22   2   4  170.4  66.9  2655    0
13  19.70  258.0  110  195.0  8.00  3.08   1   3  171.5  77.0  3375    1
14  20.30  140.0   83  109.0  8.40  3.40   2   4  168.8  69.4  2700    0
15  17.80  302.0  129  220.0  8.00  3.00   2   3  199.9  74.0  3890    1
16  14.39  500.0  190  360.0  8.50  2.73   4   3  224.1  79.8  5290    1
17  14.89  440.0  215  330.0  8.20  2.71   4   3  231.0  79.7  5185    1
18  17.80  350.0  155  250.0  8.50  3.08   4   3  196.7  72.2  3910    1
19  16.41  318.0  145  255.0  8.50  2.45   2   3  197.6  71.0  3660    1
20  23.54  231.0  110  175.0  8.00  2.56   2   3  179.3  65.4  3050    1
21  21.47  360.0  180  290.0  8.40  2.45   2   3  214.2  76.3  4250    1
22  16.59  400.0  185    NaN  7.60  3.08   4   3  196.0  73.0  3850    1
23  31.90   96.9   75   83.0  9.00  4.30   2   5  165.2  61.8  2275    0
24  29.40  140.0   86    NaN  8.00  2.92   2   4  176.4  65.4  2150    0
25  13.27  460.0  223  366.0  8.00  3.00   4   3  228.0  79.8  5430    1
26  23.90  133.6   96  120.0  8.40  3.91   2   5  171.5  63.4  2535    0
27  19.73  318.0  140  255.0  8.50  2.71   2   3  215.3  76.3  4370    1
28  13.90  351.0  148  243.0  8.00  3.25   2   3  215.5  78.5  4540    1
29  13.27  351.0  148  243.0  8.00  3.26   2   3  216.1  78.5  4715    1
30  13.77  360.0  195  295.0  8.25  3.15   4   3  209.3  77.4  4215    1
31  16.50  360.0  165  255.0  8.50  2.73   4   3  185.2  69.0  3660    1

In [19]:
auto = gasoline[gasoline.x11 == 1].y

In [20]:
manual = gasoline[gasoline.x11 == 0].y

In [23]:
scst.shapiro(manual)

ShapiroResult(statistic=0.905103325843811, pvalue=0.28309041261672974)

In [22]:
scst.shapiro(auto)

ShapiroResult(statistic=0.978470504283905, pvalue=0.8785321712493896)

In [24]:
scst.bartlett(manual, auto)

BartlettResult(statistic=5.830658668836262, pvalue=0.015749225692643542)

In [27]:
scst.ttest_ind(manual, auto, axis = 0, equal_var = False, alternative = 'greater')

Ttest_indResult(statistic=4.654947063750356, pvalue=0.000490536693828094)

In [35]:
locate = pd.read_csv('./locate.txt', delimiter = ' ')

In [37]:
front = locate[locate.location == 'F'].sales

In [40]:
middle = locate[locate.location == 'M'].sales

In [41]:
rear = locate[locate.location == 'R'].sales

In [44]:
scst.shapiro(front)

ShapiroResult(statistic=0.9792824983596802, pvalue=0.9479360580444336)

In [45]:
scst.shapiro(middle)

ShapiroResult(statistic=0.9580121636390686, pvalue=0.8042968511581421)

In [46]:
scst.shapiro(rear)

ShapiroResult(statistic=0.9280329942703247, pvalue=0.5649998188018799)